import { Box } from "@mui/material"
import { AppWrapper } from '../lib/appState'
import Head from 'next/head'
import { Container } from '@mui/system'

function MyApp({ Component, pageProps }) {
  return <Container>
    <AppWrapper>
      <Head>
        <title>My personal trader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" justifyContent="center" padding="2rem">
        <Component {...pageProps} />
      </Box>
    </AppWrapper>
  </Container>
}

export default MyApp
