// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSession struct {
	Signature string `json:"signature"`
	Message   string `json:"message"`
}

type NewStopLossFollower struct {
	TradeID              string  `json:"tradeID"`
	FollowUpPercent      float64 `json:"FollowUpPercent"`
	InitialStopLossPrice float64 `json:"InitialStopLossPrice"`
}

type NewTrade struct {
	LeftCoin       string   `json:"leftCoin"`
	RightCoin      string   `json:"rightCoin"`
	AmountLeftCoin float64  `json:"amountLeftCoin"`
	MarketBuy      bool     `json:"MarketBuy"`
	BuyPrice       *float64 `json:"BuyPrice"`
}

type StopLossFollower struct {
	Trade                *Trade  `json:"trade"`
	FollowUpPercent      float64 `json:"FollowUpPercent"`
	InitialStopLossPrice float64 `json:"InitialStopLossPrice"`
	CurrentStopLossPrice float64 `json:"CurrentStopLossPrice"`
	SoldTime             *string `json:"SoldTime"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Trade struct {
	ID              string  `json:"id"`
	LeftCoin        string  `json:"leftCoin"`
	RightCoin       string  `json:"rightCoin"`
	AmountFirstCoin float64 `json:"amountFirstCoin"`
	CreationTime    string  `json:"CreationTime"`
	BuyPrice        float64 `json:"BuyPrice"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
